### ISSUE TITLE
MagicNumberCheck: enum abstract values should be ignored

### ISSUE THREAD

**Issue by Gama11** [adireddy/haxe-checkstyle#104] opened 2016-03-05 13:38 UTC
We currently have this in our `static-analysis.txt`:

```
src/checkstyle/reporter/BaseReporter.hx:119: characters 11-13 : Info: Magic number "91" detected - consider using a constant
src/checkstyle/reporter/BaseReporter.hx:120: characters 12-14 : Info: Magic number "94" detected - consider using a constant
src/checkstyle/reporter/BaseReporter.hx:121: characters 15-17 : Info: Magic number "95" detected - consider using a constant
```

Caused by:

``` haxe
@:enum
abstract Style(Int) {
    var BOLD = 1;
    var RED = 91;
    var BLUE = 94;
    var MAGENTA = 95;
}
```

Values in enum abstract are implicitly `inline` and should be ignored.

**Comment by adireddy** [comment] 2016-03-06 08:37
fixed in dev

**Comment by RblSb** [comment] 2018-07-08 12:32
I have this problem with the default config (haxe 3.4.7 / 4.0) if enum abstract is not in a separate file.

**Comment by AlexHaxe** [comment] 2018-07-08 12:57
MagicNumber, Type und VariableInitialisation checks currently only support haxe 3.4 syntax (`@:enum abstract`). 
Checkstyle has some support for Haxe 4 syntax, but there are still some areas that need fixing - also Haxe 4 syntax is not fully finalized...

I'll take a look.

**Comment by RblSb** [comment] 2018-07-08 13:10
@AlexHaxe, I understand, but I tested on `@:enum abstract Style` above, so the problem is not only to support the `enum abstract` syntax from haxe 4, but also to use it in a file along with other data, it seems.

**Comment by AlexHaxe** [comment] 2018-07-08 13:18
ok, in my short tests it worked for `@:enum abstract` but not for `enum abstract`. Maybe my testcase is incomplete.

Can you post a short example?

**Comment by RblSb** [comment] 2018-07-08 14:00
No problem. If you comment out the class, everything works, otherwise it returns warnings about magic numbers (checkstyle 2.4.2, haxe 3.4.7).
`CodeStyle.hx`
```
@:enum
abstract Style(Int) {

	var BOLD = 1;
	var RED = 91;
	var BLUE = 94;
	var MAGENTA = 95;

}

class CodeStyle {

	public function new() {}

}
```

**Comment by AlexHaxe** [comment] 2018-07-08 15:11
Interesting... if you place `@:enum abstract` at the bottom of your file, it won't complain (= my previous testcase). 
Very strange.

**Comment by RblSb** [comment] 2018-07-09 03:38
This is because of this line https://github.com/HaxeCheckstyle/haxe-checkstyle/blob/dev/src/checkstyle/checks/coding/MagicNumberCheck.hx#L24
`forEachField` checks all fields of all structures, so the value of `ignore` is taken from the last field of the last structure (`parent.kind` is `CLASS` in example below). It is necessary to check each "parent" separately and ignore the necessary ones (for example, create an array of filtered parents).  I think you know the best option, how to fix it, hope I helped :)

**Closed as completed** 2018-07-09 17:22 UTC
Labels: bug
